### PR TITLE
Admin

### PR DESCRIPTION
**Pull request by SirZach**
@Createor I wanted to at least get player administration out the door as part of admin functionality even though it doesn't include League or Season administration.

I'm hoping for some harsh feedback on this. Let me know!

### CODE REVIEW

**Comment by SirZach** [comment]
In order for this to be merged in, the real foosball firebase will have to have a few updates.

**Comment by Createor** [comment]
User admin needs to be able to see all players' games played

**Comment by Createor** [comment]
Quick actions needed for User line in User Admin page:
Promote/Demote to ranked user. This should be an up or down arrow with hover text "Click to Promote to Ranked User" or "Click to Demote to Ranked User", respectively
Retire/Activate user.

These should be over on the left by the Edit button

**Comment by Createor** [comment]
The edit button should be the expected pencil icon.

**Comment by Createor** [comment]
Boolean flags in the Edit user modal should be toggles, rather than dropdowns.

**Comment by Createor** [comment]
Anywhere on the row in the user list should be clickable to edit the user

**Comment by Createor** [comment]
'Met minimum games' should be changed to Ranked/Unranked

**Comment by Createor** [comment]
'Met minimum games'  and 'Retired' should be toggles, rather than dropdowns

**Comment by Createor** [comment]
Name and Slack should be required fields

**Comment by SirZach** [comment]
@Createor I think I've addressed all of your feedback except for being able to see all of a player's games. You can see this by selecting a player from the home page and then looking at their games but there is no admin functionality to edit a game yet.

**Pull request merged**
