### PR TITLE
League admin

### LINKED ISSUE #138: league administration for global admins
The first part of the admin work is to allowing for administration within a particular league to edit players. Now we need global admins to have access to create and edit leagues themselves.

### PR DESCRIPTION
**Pull request by SirZach**
closes #138

### CODE REVIEW

**Comment by Createor** [comment]
Is/Should a new league be populated with a default season?

**Comment by SirZach** [comment]
it is not currently...but it probably should? what are the proposed dates for the default season? from creation until 3 months from creation?

**Comment by Createor** [comment]
I think that'd be reasonable.

**Comment by SirZach** [comment]
i can do that.

**Comment by SirZach** [comment]
i'll merge this guy tomorrow pending travis checks

**Pull request merged**
