### PR TITLE
Seasons

### LINKED ISSUE #139: Season administration
After league administration, admins need the ability to add and edit seasons.

Seasons consist of

• name
• start date
• end date
• isActive

### PR DESCRIPTION
**Pull request by SirZach**
closes #139

### CODE REVIEW

**Comment by SirZach** [comment]
note: this is for season administration, not for using seasons throughout the app

**Comment by SirZach** [comment]
https://dev-foosball-pr-142.herokuapp.com/admin?section=seasons

**Comment by TheConnMan** [comment]
I'm getting redirected away from the admin page. Do I need to be promoted to an admin?

**Comment by Createor** [comment]
That works great on mobile, aside from minor display quirks on the calendar!!

**Pull request merged**
